### ISSUE TITLE
Risk | org.projectlombok.lombok 

### ISSUE THREAD

**Issue by hynamedev** [hynamedev/ZuneAPI#1]
# Lombok Pros & Cons

**Pros:**
- Simplifies development process
- Simple

**Cons:**
- Relies on non-public APIs
- Uses unsafe methods to modify `javac` on the fly
- Makes code harder to understand

(Was gonna remove it soon anyway so might as well put it here)

**Comment by BigRobotBil** [comment]
Would you be replacing Lombok with something else similar, or revert to writing the boilerplate getters/setters/constructors/etc?

**Comment by hynamedev** [comment]
> Would you be replacing Lombok with something else similar, or revert to writing the boilerplate getters/setters/constructors/etc?
I don’t currently know any great replacements so currently its being replaced w/ plain getters & setters (+ constructors)

**Comment by hynamedev** [comment]
Resolved (See `f210aa4`)

> # Lombok Pros & Cons
> **Pros:**
> 
> * Simplifies development process
> * Simple
> 
> **Cons:**
> 
> * Relies on non-public APIs
> * Uses unsafe methods to modify `javac` on the fly
> * Makes code harder to understand
> 
> (Was gonna remove it soon anyway so might as well put it here)
